### ISSUE TITLE
Cannot stream .m3u URLs

### ISSUE THREAD

**Issue by ghost** [jackpoz/OnlineRadio#10]
Attempting to stream `https://edg-iad-wunc-ice.streamguys1.com/wunc-128-aac.m3u` or `https://edg-iad-wunc-ice.streamguys1.com/wunc-128-mp3.m3u` fails but still works in VLC and in browser.

**Comment by jackpoz** [comment]
https://github.com/jackpoz/OnlineRadio/commit/c97c8510fdee8e01dbcf2a82346ef70224c5ab4c
