### ISSUE TITLE
.NET Core 3 support

### ISSUE THREAD

**Issue by ghost** [jackpoz/OnlineRadio#8]
As .NET Core gets closer to GA I think support for it should be explored since it provides cross platform support and performance boosts. Not to mention that migration will be necessary when .NET 5 is released.

In moving I found these resources useful:
- https://github.com/hvanbakel/CsprojToVs2017
- https://devblogs.microsoft.com/dotnet/how-to-port-desktop-applications-to-net-core-3-0/
- https://docs.microsoft.com/en-us/dotnet/core/porting/wpf

**Comment by jackpoz** [comment]
It's a bit disappointing that the Microsoft documentation to migrate the VS project is a list of manual steps. I will see if trying before .NET Core 3 is released or wait for it, it depends on the amount of free time.
The missing support of the designer is also annoying (but I hope they will add support to it one day)

**Comment by jackpoz** [comment]
https://github.com/jackpoz/OnlineRadio/pull/12
